services:
  valkey:
    image: valkey/valkey:8.1.2-alpine
    command: "valkey-server --port 6379"
    ports:
      - "6379:6379"
    networks:
      - tazama
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli -p 6379 ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  tazama-db:
    image: postgres:17.5-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5432:5432"
    networks:
      - tazama
    volumes:
      - tazama-db:/data/postgres
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  nats:
    image: nats:2.11-alpine
    entrypoint: nats-server
    command: ["-m", "8222"]
    networks:
      - tazama
    ports:
      - "4222:4222"
      - "8222:8222"

networks:
  tazama:

volumes:
  tazama-db:
